### ISSUE TITLE
Usecase of IdentityLinkedMap (question)

### ISSUE THREAD

**Issue by ghost** [futuresimple/android-db-commons#72]
Why don't you just use IdentityHashMap provided by JDK instead of IdentityLinkedMap?

**Comment by chalup** [comment]
I can't for the life of me remember the reason. Most likely explanation: brainfart. Second most likely explanation: someone decided to go perfnazi and implemented it instead of wrapping `IdentityHashMap` into `Collections.synchronizedMap()`.

Either way, we don't have 100% code coverage in ComposedCursorLoader so I'm going to apply "if it ain't broke don't fix it" rule and keep it in place.
